import useSSRTranslation from 'common/hooks/useSSRTranslation'
import { Button } from 'components/test'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import styles from 'styles/Home.module.css'

const Home: NextPage = () => {
  const { t, toggleLanguage } = useSSRTranslation()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {t('test')}
      <Button onClick={toggleLanguage}>Change language</Button>
      <Link href="/">Back to page 1</Link>
    </div>
  )
}

export async function getServerSideProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'footer'])),
      // Will be passed to the page component as props
    },
  }
}

export default Home
