name: Lint

on:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          
      - run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint
